version: '3.8'

services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S api:8000 -t public
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33061:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dump-sql:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql:rw
volumes:
  mysql-data:


